#### GET / endpoint
GET http://localhost:3000

#### sign up a user
POST http://localhost:3000/api/staff/signup
Content-Type: application/json 


{
     "email": "vkpinto1234@gmail.com",
    "name": "new commer",
    "password": "123456"



}

### admin sign up a staff
POST  http://localhost:3000/users/admin/addStaff
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU0NTc3NjQyfQ.iY-FFCFUd5IPMytBCHOgcVNSwALoYSQqz-q6tGZX0Aw

{
    "email": "emmanuelofotsukwablaagbovie@gmail.com",
    "name": "Emmanuel",
    "role": "staff"


}




#### login a user
POST http://localhost:3000/api/staff/login
Content-Type: application/json

{
    "email": "vkpinto1234@gmail.com",
    "password": "123456"


}

### get user profile
GET http://localhost:3000/users/staff/profile
Authorization: Bearer 
### update user profile
PUT  http://localhost:3000/users/staff/profile
Authorization: Bearer 
Content-Type: application/json 

{
  "name": "new comer",
  "email": "newcomer@gmail.com",
   "password": "123456",
   "role" :"staff",
    "classTaught":"class 6",
    "subject": "maths",
    "contact":"0255555555",
    "address": "123 raspberry steet"

}



### delete user profile
DELETE http://localhost:3000/users/staff/profile
Authorization: Bearer 



### staff submit leave
POST http://localhost:3000/users/staff/leave
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InN0YWZmIiwiaWF0IjoxNzU0NTgzMzY3fQ.kopRgPYzA0jSZz27DJ30ch5hUrCQQ_A0-s8j0T7ri_w

{"reason": "study room leave",
  "start_date": "2025-06-11",
  "end_date": "2025-06-1"
  
} 

### staff view announcements
GET http://localhost:3000/users/staff/announcements
Authorization: Bearer 

### staff submit suggestions
POST http://localhost:3000/users/staff/suggestions
Authorization: Bearer 
Content-Type: application/json

{
  "suggestion": "improve the school infrastructure"
  
}

### staff view leave application responce
GET http://localhost:3000/users/staff/leaveResponce
Authorization: Bearer 
### staff submits TLMs
POST http://localhost:3000/users/staff/submitTLMs
Authorization: Bearer 
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="title"

Introduction to sample subject

--MyBoundary
Content-Disposition: form-data; name="description"

Week 1 lesson note covering basics of sample subject
--MyBoundary
Content-Disposition: form-data; name="file"; filename="sample.pdf"
Content-Type: application/pdf

 ../sample.pdf
--MyBoundary--




### admin signup
POST http://localhost:3000/api/admin/signup
Content-Type: application/json

{
 "name" : "victor pinto",
 "email" : "vkpinto@gmial.com",
 "password" : "iamalive",
 "role" : "admin"
}

### get user profile
GET http://localhost:3000/users/user/profile
Authorization: Bearer 

### admin login
POST http://localhost:3000/api/admin/login
Content-Type: application/json

{
  "email": "vkpinto@gmial.com",
  "password": "iamalive"
}


### get Admin profile
GET http://localhost:3000/users/admin/profile
Authorization: Bearer 


### admin get all staff profiles
GET http://localhost:3000/users/admin/staffProfiles
Authorization: Bearer 

### admin get all staff leaveApplications
GET http://localhost:3000/users/admin/leaveApplications
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU0NTgzNDE5fQ.ZvJjC6369Uf6IETinQmH85k_IQh5khsX_9TMu58sPA0

### admin get staff leaveApplications by ID
GET http://localhost:3000/users/admin/leaveApplications/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU0NTgzNDE5fQ.ZvJjC6369Uf6IETinQmH85k_IQh5khsX_9TMu58sPA0



### admin approve leave application
PUT http://localhost:3000/users/admin/LeaveApplication/approve
Authorization: Bearer 
Content-Type: application/json

{
 "email": "EmmaAgbovie@gmail.com"
}

### admin reject leave application
PUT http://localhost:3000/users/admin/LeaveApplication/reject
Authorization: Bearer 
Content-Type: application/json

{
 "email": "EmmaAgbovie@gmail.com"
}

### admin views all staff submitted TLMs
GET http://localhost:3000/users/admin/viewTLMs
Authorization : Bearer 

### admin broadcasts announcements
POST http://localhost:3000/users/admin/announcement
Authorization: Bearer 
Content-Type: application/json

{
  "announcementTitle": "Test Announcement",
  "announcement": "This is a test announcement"

}

### admin view suggestions
GET http://localhost:3000/users/admin/viewSuggestions
Authorization: Bearer 








### admin deletes user profile
DELETE http://localhost:3000/users/admin/delete
Content-Type: application/json
Authorization: Bearer 

{
  "email": "example@gmail.com"
}