#### GET / endpoint
GET http://localhost:3000

#### sign up a user
POST http://localhost:3000/api/staff/signup
Content-Type: application/json 


{
     "email": "Testuser1@gmail.com",
    "name": "Testuser",
    "password": "1234567890"



}

### admin sign up a staff
POST  http://localhost:3000/users/admin/addStaff
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU1Nzc1Nzc2fQ.bqGIjMcrE8eyGaxoWsfLD7ae3060IjGnNMnSkuxU4PA

{
    "email": "efuamichelle18@gmail.com",
    "name": "Michelle Efua Adams",
    "role": "staff"


}




#### login a user
POST http://localhost:3000/api/staff/login
Content-Type: application/json

{
    "email": "Testuser1@gmail.com",
    "password": "1234567890"


}

### get user profile
GET http://localhost:3000/users/staff/profile
Authorization: Bearer 
### update user profile
PUT  http://localhost:3000/users/staff/profile
Authorization: Bearer 
Content-Type: application/json 

{
  "name": "new comer",
  "email": "newcomer@gmail.com",
   "password": "123456",
   "role" :"staff",
    "classTaught":"class 6",
    "subject": "maths",
    "contact":"0255555555",
    "address": "123 raspberry steet"

}



### delete user profile
DELETE http://localhost:3000/users/staff/profile
Authorization: Bearer 



### staff submit leave
POST http://localhost:3000/users/staff/leave
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InN0YWZmIiwiaWF0IjoxNzU1NjQzMDg5fQ.lVTGbYSs8bHI2vKDGWQUUKn2nvu3NWedTVqRT8LpCoE

{"reason": "work emergency",
  "start_date": "2025-06-11",
  "end_date": "2025-06-1"
  
} 

### staff view announcements
GET http://localhost:3000/users/staff/announcements
Authorization: Bearer 

### staff submit suggestions
POST http://localhost:3000/users/staff/suggestions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InN0YWZmIiwiaWF0IjoxNzU1NjQzMDg5fQ.lVTGbYSs8bHI2vKDGWQUUKn2nvu3NWedTVqRT8LpCoE
Content-Type: application/json

{
  "suggestion": "improve the library resources "

}

### staff view leave application responce
GET http://localhost:3000/users/staff/leaveResponce
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InN0YWZmIiwiaWF0IjoxNzU1NTQyNTI2fQ.XyiySzMq9ICBsi1v6ghKqqmnTssj-CzlOfMTjer_YhQ

### staff submits TLMs
POST http://localhost:3000/users/staff/submitTLMs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InN0YWZmIiwiaWF0IjoxNzU1NzkyNzc5fQ.ihBlq4DbuDnqsddH97E33pZeQIC2QMKOXlhdyWr8Fm4
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="title"
Introduction to sample subject

--MyBoundary
Content-Disposition: form-data; name="original_name"
sample subject TLM

--MyBoundary
Content-Disposition: form-data; name="description"
Week 1 lesson note covering basics of sample subject
--MyBoundary
Content-Disposition: form-data; name="file"; filename="sample.pdf"
Content-Type: application/pdf

 ../sample.pdf
--MyBoundary--


### staff submits TLMs (updated version)
POST http://localhost:3000/users/staff/submitTALMs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InN0YWZmIiwiaWF0IjoxNzU1NjQzMDg5fQ.lVTGbYSs8bHI2vKDGWQUUKn2nvu3NWedTVqRT8LpCoE

{
  "week": "1",
  "topic": " basics of sample subject",
  "notes": "this is a sample lesson note for week 1"
}





### admin signup
POST http://localhost:3000/api/admin/signup
Content-Type: application/json

{
 "name" : "victor pinto",
 "email" : "vkpinto@gmial.com",
 "password" : "iamalive",
 "role" : "admin"
}

### get user profile
GET http://localhost:3000/users/user/profile
Authorization: Bearer 

### admin login
POST http://localhost:3000/api/admin/login
Content-Type: application/json

{
  "email": "vkpinto@gmial.com",
  "password": "iamalive"
}


### get Admin profile
GET http://localhost:3000/users/admin/profile
Authorization: Bearer 


### admin get all staff profiles
GET http://localhost:3000/users/admin/staffProfiles/1
Authorization: Bearer 

### admin get all staff leaveApplications
GET http://localhost:3000/users/admin/leaveApplications
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU1NjQzMzAwfQ.jCqoznx3wLlP9HLqNEx2CMBdOarFnogUvZNiFKhZEhM

### admin get staff leaveApplications by ID
GET http://localhost:3000/users/admin/leaveApplications/2
Authorization: Bearer 



### admin approve leave application
PUT http://localhost:3000/users/admin/LeaveApplication/approve
Authorization: Bearer 
Content-Type: application/json

{
 "email": "EmmaAgbovie@gmail.com"
}

### admin reject leave application
PUT http://localhost:3000/users/admin/LeaveApplication/reject/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU1NTQyNzg0fQ.3zT_Bqa_Wm2xPlnAcGOmmVbHoVm36jqnv56IU6KFrYY



### admin views all staff submitted TLMs
GET http://localhost:3000/users/admin/viewTLMs
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU1NzkyODUzfQ.watG8zLzEBEQZnknz00FqFpVMUasqpp56fdwIVe6Ixc
### admin views all staff submitted TLMs (updated version)
GET http://localhost:3000/users/admin/viewTALMs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU1NjQzMzAwfQ.jCqoznx3wLlP9HLqNEx2CMBdOarFnogUvZNiFKhZEhM

### admin broadcasts announcements
POST http://localhost:3000/users/admin/announcement
Authorization: Bearer 
Content-Type: application/json

{
  "announcementTitle": "Test Announcement",
  "announcement": "This is a test announcement"

}

### admin view suggestions
GET http://localhost:3000/users/admin/viewSuggestions/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU1NTQyNzg0fQ.3zT_Bqa_Wm2xPlnAcGOmmVbHoVm36jqnv56IU6KFrYY

### get admin stats
GET http://localhost:3000/users/admin/stats
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU1NjQzMzAwfQ.jCqoznx3wLlP9HLqNEx2CMBdOarFnogUvZNiFKhZEhM







### admin deletes user profile
DELETE http://localhost:3000/users/admin/delete
Content-Type: application/json
Authorization: Bearer 

{
  "email": "example@gmail.com"
}